drop table if exists dog CASCADE;

create table dog (
       dog_id bigint generated by default as identity,
        dog_birth_date date not null,
        dog_description varchar(255),
        dog_name varchar(100) not null,
        dog_species varchar(25) not null,
        dog_weight varchar(20) not null,
        member_id bigint not null,
        primary key (dog_id)
    );

drop table if exists member CASCADE;

    create table member (
           member_id bigint generated by default as identity,
            email varchar(255) not null,
            member_status varchar(255),
            nickname varchar(255) not null,
            password varchar(255) not null,
            sign_up_at timestamp,
            primary key (member_id)
        );

drop table if exists reservation CASCADE;

    create table reservation (
           reservation_id bigint generated by default as identity,
            hair_option varchar(20) not null,
            reserve_date date not null,
            reserve_time time not null,
            dog_id bigint not null,
            hair_shop_id bigint not null,
            member_id bigint not null,
            primary key (reservation_id)
        );

drop table if exists hair_shop CASCADE;

    create table hair_shop (
       hair_shop_id bigint generated by default as identity,
        hair_shop_address varchar(100) not null,
        hair_shop_description clob,
        hair_shop_image clob,
        hair_shop_name varchar(50) not null,
        hair_shop_phone varchar(255) not null,
        primary key (hair_shop_id)
    );

drop table if exists review CASCADE;

    create table review (
           review_id bigint generated by default as identity,
            created_at timestamp not null,
            last_modified_at timestamp,
            review_image varchar(255),
            review_text varchar(255) not null,
            hair_shop_id bigint not null,
            member_id bigint,
            reservation_id bigint,
            primary key (review_id)
        );



--CREATE TABLE test_entity (
--  id INT PRIMARY KEY,
--  name VARCHAR(255),
--  addr VARCHAR(255)
--);
--
--LOAD DATA LOCAL INFILE '/Users/sangyoonlee/Downloads/DistrictOffice.csv'
--INTO TABLE district_office
--FIELDS TERMINATED BY ','
--ENCLOSED BY '"'
--LINES TERMINATED BY '\n'
--IGNORE 1 ROWS
--(district_office_id, name, address, latitude, longitude, keyword);
----
--
--LOAD DATA LOCAL INFILE '/Users/sangyoonlee/Downloads/exceldata.csv'
--INTO TABLE excel_list
--FIELDS TERMINATED BY ','
--ENCLOSED BY '"'
--LINES TERMINATED BY '\n'
--IGNORE 1 ROWS
--(id, addr);