spring:
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      schema-locations: classpath*:h2/schema.sql
      data-locations: classpath*:h2/data.sql